# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8816bd3c3ae6657941c8c320b7f105298e4232362fd005532a9e7f30b84e16a65da09d465f5655fc5bbc738e2ce7967f339ac1f815d577acfe13973a462ea251

test:
  secret_key_base: c5ad7ba6e78237e99381b19699a829733f2fba098954b9a9748c9d05bbf7b31f6ef7edb2590dc76c917b6644a603fd31a3618ca1649d1a509842ec28e06b78ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
